### ISSUE TITLE
Check Pts Animation Performance

### ISSUE THREAD

**Issue by robert-claypool** [gisbiz/website#2]
My machine CPU/GPU fan runs high after about 5 minutes on https://ptsjs.org and the same occurs on our site.

We need to reduce this impact - stop the animation after 1 minute, or reduce frame rate, or something else. The animation looks great, but our site should not be so resource intensive on user devices.

**Comment by robert-claypool** [comment]
By the way, I noticed this on a MacBook Pro 2018, so it's an issue even for great hardware.

**Comment by harman052** [comment]
I just analyzed the https://refresh.gisbiz.com using Chrome dev tools and didn't found any performance issues. Even at 4x CPU slowdown, it worked fine.

**Comment by robert-claypool** [comment]
On Windows 10 (good hardware), GPU usage ranges between 3-8 percent. It goes to zero when the tab is not active or Chrome is minimized. I'll get metrics for Chrome on OSX and Linux.

**Comment by harman052** [comment]
> On Windows 10 (good hardware), GPU usage ranges between 3-8 percent. It goes to zero when the tab is not active or Chrome is minimized. I'll get metrics for Chrome on OSX and Linux.

Yes, the CPU consumption is relatively high but I didn't felt a performance lag while running Chrome and FireFox (each having more than 10 tabs open), VS code, terminals, docker.

PS: I am watching https://refresh.gisbiz.com/ not https://ptsjs.org.

**Comment by robert-claypool** [comment]
The 60 second lifetime is working well on all my devices. I think that's good enough to close this issue. Reopen if you notice poor performance.
